site_name: Ganesh Venepally
theme:
  name: material
  # custom_dir: overrides
  # icon:
  #   logo: fontawesome/solid/laptop-code
  favicon: ./favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - content.tabs.link

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details

nav:
  - Home: 'index.md'
  - Network Automation:
    - Intro: network-automation/index.md
    - NetDevOps: network-automation/01-netdevops/index.md
    - Data Models and Encodings: network-automation/02-data-models-encodings/index.md
  # - About: 'about.md'

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ganeshvenepally
    - icon: fontawesome/brands/github 
      link: https://github.com/ganeshvenepally/ganeshvenepally
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ganesh-venepally/
